schemaVersion: 1.0.0
name: chainbridge-ai

dev:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

default:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://rpc.ankr.com/eth_sepolia
