
# ==========================================================================
dev:
  user-workflow:
    workflow-name: "bridge-execution-dev"
  workflow-artifacts:
    workflow-path: "./src/workflow.ts"
    config-path: "./config.dev.json"
    secrets-path: ""
